# SPDX-License-Identifier: GPL-2.0+

obj-y	+= ipq5332.o
obj-$(CONFIG_VENDOR_TLT) += gpio.o
obj-$(CONFIG_VENDOR_TLT) += board.o
obj-$(CONFIG_VENDOR_TLT) += mnf_flash.o
obj-$(CONFIG_VENDOR_TLT) += mnf_fields.o
obj-$(CONFIG_VENDOR_TLT) += fsb_flash.o
