#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=10

PROG="/usr/local/bin/ais_gps_logger.sh"

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh "$PROG"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn 3600 5 0   # Respawn if it exits (retry indefinitely, 5 seconds delay)
    procd_close_instance
}

stop_service() {
    # procd handles stopping the process automatically
    true
}
